### ISSUE TITLE
A list of concerns I've found.

### ISSUE THREAD

**Issue by amzelee** [AceTheEldritchKing/Cataclysm_Spellbooks#2]
Glad to see the mod released. I've gone ahead and listed issues and concerns here though I might not have covered all.

Firstly, **Abyssal Beam**.
Unsure if it is intended but when enemies are hit it gives them an effect that teleports them. This is problematic as Abyssal Beam takes a while to trigger after casting. The teleport makes it so that the beam becomes negligible. You can remove the teleport effect that it adds, and increase the speed at which it activates.

Visually, **Abyssal Beam** looks flat which is understandable as it was taken from the warlock from cataclysm. Maybe double the beam, one facing X and one facing Z. This turns it into a cross shaped beam which will definitely improve visuals. Additionally you can also consider making it actually 2 beams worth of damage to increase the lethality of the spell. Of course this should be discussed and considered more as this now concerns balance.

Secondly, **Abyssal Blast** takes too long of a cooldown. Additionally, it would be preferrable that you are able to move your player camera during the cast time even if it's just slightly. Currently it locks your PoV into place, and only allow you to move when nearing the end of the spell duration.

Thirdly, **Dimensional Rift** doesn't seem to abide by the no spell griefing rule in the config. If possible, add an option to make it so that it doesn't destroy the surroundings.

Fourth, **Tidal Tear** doesn't always release a visual effect when used. The echo VFX that it should release doesn't appear  and it ends up looking as if the mob had died from nothing.

Lastly, **Tidal Laceration's** condition to activate should be set to "requires target". 

Overall, just tweaks to cooldowns, mana, and damage will ultimately make the mod especially demanded and appreciated. These are things I've mostly noticed during my tests and does not contain all concerns possible. Anyhow, great job with the mod. Looking forward to it getting updates and improvements in the future!

**Comment by AceTheEldritchKing** [comment]
Hello! I appreciate your feedback! Unfortunately, some of your requests would be hard to do as the spells are summoning entities handled by Cataclysm itself. The effects that Abyssal Beam inflicts and the visuals of it would require me to change Cataclysm's code itself, which something I would wish to avoid if possible. I'm sorry if this might be disappointing news to hear. Also, the player having their POV locked is intentional, as the Abyssal Blast beam only works in one direction. If the player were to move their head,  it would only show the visuals of the beam moving, but not the actually damage itself. That's just how it is in the entity class. However! I can try to see if I can change the Dimension Rift to abide by griefing, I just have to see how Cataclysm handles it. You might have to look into the Cataclysm configs to adjust it if the option is there. I'll also try to see if I can adjust the SFX/VFX of Tidal Tear and adjust how Tentacle Laceration targets enemies. Thank you again for the feedback, I really appreciate it!

**Comment by AceTheEldritchKing** [comment]
I recently checked, and how Cataclysm handles the griefing of the Dimensional Rift is through Minecraft's gamerules. You'll have to disable Mob Griefing in your world for it to take place. The method that handles this is a private method (laymans terms, I cannot access it directly without using a mixin to change the code). If there is an issue with it, you may have to consult the Cataclysm devs about the griefing rules
